### ISSUE TITLE
执行python3 auto_spy_bot2.py命令后报Server disconnected

### ISSUE THREAD

**Issue by yanzhengui** [xieshang/AutoSpy#28]
如题，修改好auto_spy.yaml配置文件后，执行python3 auto_spy_bot2.py命令时，报异常Server disconnected，但是日志中没有写明是哪里的服务连不上，请问需要怎么处理？具体一场日志如下：

`准备登录青龙:
2022-12-31 12:52:14,431 - /usr/lib64/python3.6/asyncio/events.py[line:145] - INFO: 
青龙1-登录成功
2022-12-31 12:52:19,375 - /usr/lib64/python3.6/asyncio/events.py[line:145] - INFO: 获取任务列表成功
2022-12-31 12:52:19,376 - /usr/lib64/python3.6/asyncio/events.py[line:145] - INFO: 龙1-开始创建执行任务
2022-12-31 12:52:19,376 - /usr/lib64/python3.6/asyncio/events.py[line:145] - INFO: 龙1-开始创建【cj组队】任务
2022-12-31 12:52:19,376 - /usr/lib64/python3.6/asyncio/events.py[line:145] - INFO: 创建任务出错:
{'Container': [[]], 'Env': 'jd_cjzd', 'KeyWord': [['频道1变量A1'], ['频道2变量A2']], 'Name': 'cj组队', 'Script': 'jd_team60.js', 'TimeOut': 0, 'Wait': 3}
string indices must be integers
加载 ./plugins  .py 插件----开始
插件信息加载成功
加载 ./plugins  .py 插件----结束
加载 ./plugins/x86_tx  .so 插件----开始
插件信息加载成功
加载 ./plugins/x86_tx  .so 插件----结束
ERROR:root:【TaskRuning】出错:
ERROR:root:Server disconnected
ERROR:root:Traceback (most recent call last):
  File "auto_spy.py", line 979, in auto_spy.TaskRuning
  File "auto_spy.py", line 288, in gettasklist
  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/root/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/root/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`

**Comment by ixmu** [comment]
请问你成功解决这个问题了吗？
