### ISSUE TITLE
执行python3 auto_spy_bot2.py报 [Errno 2] No such file or directory: 'auto_spy.so_x86_64'

### ISSUE THREAD

**Issue by wgxatc** [xieshang/AutoSpy#40]
root@auto_spy:/autospy# python3 auto_spy_bot2.py
sys info:uname_result(system='Linux', node='auto_spy', release='3.10.0-1160.71.1.el7.x86_64', version='#1 SMP Tue Jun 28 15:37:28 UTC 2022', machine='x86_64', processor='')
Traceback (most recent call last):
  File "auto_spy_bot2.py", line 18, in <module>
    shutil.copy("auto_spy.so_x86_64", "auto_spy.so")
  File "/usr/local/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'auto_spy.so_x86_64'

**Comment by liwenjie119** [comment]
仓库删除了这个文件，只保留了auto_spy.so_x86_64_2，但是教程中的方法还需要这个文件
