### ISSUE TITLE
spy升级后无法运行，提示缺失组件

### ISSUE THREAD

**Issue by Mousehk** [xieshang/AutoSpy#48]
root@auto_spy:/autospy# python3 auto_spy_bot.py
sys info:uname_result(system='Linux', node='auto_spy', release='5.15.103', version='#0 SMP Tue Mar 21 14:20:33 2023', machine='x86_64', processor='')
系统为 x86_tx
Traceback (most recent call last):
  File "auto_spy_bot2.py", line 28, in <module>
    from auto_spy import main
  File "auto_spy.py", line 9, in init auto_spy
ModuleNotFoundError: No module named 'Crypto'

提示缺少组件但pip3 install Crypto还是pip3 install requests[Crypto] 安装后重启后还是提示同样的错误

**Comment by Mousehk** [comment]
固件版本openwrt 5.15.103 
没升级之前417版本用着好好的，更新最新spy出现该问题，docker卸载重装问题同样。

**Comment by mouse1130** [comment]
和你遇到同样的问题

**Comment by mouse1130** [comment]
退回417版本了下载417文件覆盖就好了
https://raw.githubusercontent.com/xieshang/AutoSpy/8740eb16c960066ce19417d549a30583e7dfd149/auto_spy.so_x86_64_2
