### ISSUE TITLE
decoder 以及 h5st31 等问题哪位大神指点下迷津，不胜感激

### ISSUE THREAD

**Issue by xuexijiaoben** [xieshang/AutoSpy#49]
问题一：
下载结果:True 0
保存文件:./config/
a bytes-like object is required, not 'str'
2023-06-13 21:16:09,798 - /usr/local/lib/python3.6/site-packages/telethon/client/updates.py - INFO: Traceback (most recent call last):
  File "auto_spy.py", line 2777, in auto_spy.downloadfile
  File "auto_spy.py", line 2778, in auto_spy.downloadfile
TypeError: a bytes-like object is required, not 'str'

问题二：
2023-06-13 21:21:03,025 - /usr/local/lib/python3.6/site-packages/telethon/client/updates.py - INFO: Traceback (most recent call last):
  File "auto_spy.py", line 2874, in auto_spy.cmd_update
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

问题三：
ModuleNotFoundError: No module named 'h5st31'

请大神指点，万分感谢呀，

**Comment by Dlian-Zero** [comment]
和你情况一模一样
