### ISSUE TITLE
青龙2.15.16测试结果存在错误

### ISSUE THREAD

**Issue by ixmu** [xieshang/AutoSpy#51]
青龙2.15.16版本下监测线报有问题，日志输出：1
`

sys info:uname_result(system='Linux', node='auto_spy', release='6.2.16-3-pve', version='#1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z)', machine='x86_64', processor='')

系统为 x86_tx

WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

/autospy

/autospy

加载参数

2023-06-25 00:00:51,239 - auto_spy_bot.py - INFO: 参数加载完成

2023-06-25 00:00:51,240 - auto_spy_bot.py - INFO: 插件信息加载成功

不使用代理

----------------------------------TaskRuning-------------------------

2023-06-25 00:00:56,946 - /usr/local/lib/python3.6/asyncio/events.py - INFO: AutoSpy V2023-06-15 16:37:52

Telegram 登录成功

苍翠 欢迎使用SPY

Spy启动完成

2023-06-25 00:00:57,329 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 开始鉴权

2023-06-25 00:00:57,932 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 普通授权鉴权成功

2023-06-25 00:00:57,933 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 

准备登录青龙:

青龙版本:['2', '15', '16']

获取到青龙token，SE和ID对啦

2023-06-25 00:00:58,040 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 

青龙1-登录成功

2023-06-25 00:00:58,097 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 获取任务列表成功

2023-06-25 00:00:58,098 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载Faker.spy

2023-06-25 00:00:58,404 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 青龙-1 登录失败

'js_config'

2023-06-25 00:00:58,430 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载重启线报信息

2023-06-25 00:00:58,430 - /usr/local/lib/python3.6/asyncio/events.py - INFO: spy 加载 ./plugins  .py 插件----开始

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 插件信息加载成功

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载插件:bean

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载 ./plugins  .py 插件----结束

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: spy 加载 ./plugins/x86_tx  .so 插件----开始

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 插件信息加载成功

2023-06-25 00:00:58,431 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载插件:bean

2023-06-25 00:00:58,449 - /usr/local/lib/python3.6/asyncio/events.py - INFO: Spy加载-->bean-->完成

2023-06-25 00:00:58,450 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载 ./plugins/x86_tx  .so 插件----结束

spy已启动完成，进入监听，去发个线报试试吧

1

===========================================

1

===========================================

1

===========================================

1

===========================================

1

===========================================

1

===========================================`

**Comment by liwenjie119** [comment]
我是这个报错，然后有一个线报底下数字就增加1
‘‘’
2023-07-28 20:08:48,254 - /usr/local/lib/python3.6/asyncio/events.py - INFO: Spy加载-->bean-->完成
2023-07-28 20:08:48,255 - /usr/local/lib/python3.6/asyncio/events.py - INFO: 加载 ./plugins/x86_tx  .so 插件----结束
2023-07-28 20:08:48,303 - /usr/local/lib/python3.6/asyncio/events.py - INFO: [Errno -2] Name or service not known
2023-07-28 20:08:48,304 - /usr/local/lib/python3.6/asyncio/events.py - INFO: Traceback (most recent call last):
  File "auto_spy.py", line 3947, in auto_spy.AuthThread
  File "auto_spy.py", line 4098, in get_token
socket.gaierror: [Errno -2] Name or service not known
‘’’

**Comment by dxyoo7** [comment]
> 青龙-1 登录失败
> 
> 'js_config'

@ixmu 看到青龙登陆失败了，我也是这日志，请问解决了吗

**Comment by bigoldye** [comment]
一样，先提示青龙登录成功，又提示青龙登录失败。
