### ISSUE TITLE
换了几台服务器都是这个问题TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by aweijll** [xieshang/AutoSpy#61]
Unhandled exception on my_event_handler
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "auto_spy.py", line 5173, in my_event_handler
  File "auto_spy.py", line 4824, in recive_message
TypeError: argument of type 'int' is not iterable

请问怎么解决啊？
弄了几天，好几台服务器，都是这样。
难到我的SPY无缘分？

**Comment by aweijll** [comment]
有人能回答一下问题吗，拜托拜托，我过几天在来看

**Comment by buzhudong** [comment]
我也遇到这个问题了，openwrt
