### ISSUE TITLE
Telethon超时问题

### ISSUE THREAD

**Issue by adeya520** [xieshang/AutoSpy#62]
更新了最新的docker镜像，添加了大佬的auto_spy.so_x86_64_2
还是出现以下错误
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 320, in _update_loop
    diff = await self(get_diff)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcbaseerrors.TimedOutError: RPCError -503: Timedout (caused by GetChannelDifferenceRequest)
Traceback (most recent call last):
  File "auto_spy_bot.py", line 29, in <module>
    main(systype)
  File "auto_spy.py", line 5185, in auto_spy.main
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 93, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 35, in _run_until_disconnected
    raise self._updates_error
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 320, in _update_loop
    diff = await self(get_diff)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcbaseerrors.TimedOutError: RPCError -503: Timedout (caused by GetChannelDifferenceRequest)

**Comment by adeya520** [comment]
仍然包prc超时问题，重启可运行，还是有这个问题，这是最新docker镜像

**Comment by rookis1** [comment]
我也是这个rpc超时的问题，不知道咋整

**Comment by jance-hui** [comment]
![image](https://github.com/xieshang/AutoSpy/assets/43159982/40ae12dd-cd49-4633-946e-95417494e0e4)
凌晨的时候直接挂掉了
