### ISSUE TITLE
运行出错，按照教程来，x86和arm都是相同的错误

### ISSUE THREAD

**Issue by Sndeok** [xieshang/AutoSpy#67]
2024-01-08 11:55:19,101 - auto_spy_bot.py - INFO: 参数加载完成
2024-01-08 11:55:19,101 - auto_spy_bot.py - INFO: 插件信息加载成功
Traceback (most recent call last):
  File "auto_spy_bot.py", line 29, in <module>
    main(systype)
  File "auto_spy.py", line 5081, in auto_spy.main
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by chunkingzou** [comment]
我也是这样，Arm机子

**Comment by Sndeok** [comment]
> 这个问题可能是你的yaml文件的属性值留空了，即使是留空也要双引号 "" 表示空。

感谢！已解决
