### ISSUE TITLE
无法监听频道Faker线报频道 -1001670294604

### ISSUE THREAD

**Issue by zhaoguomanong** [xieshang/AutoSpy#69]
今天突然发现无法监听频道-1001670294604, 自己创建的群可以正常监听, 另外Faker线报群-1001712811852 可以正常监听。
怀疑现在所有得channel类型的都无法监听，请问这种问题如何debug查原因？

我想让auto_spy容器打印更多日志 有开关控制吗？ spy debug命令直接导致程序报错， 帮忙看看怎么fix:

2024-04-10T10:30:25.577322428Z Unhandled exception on my_event_handler
2024-04-10T10:30:25.577396711Z Traceback (most recent call last):
2024-04-10T10:30:25.577409105Z   File "/usr/local/lib/python3.6/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
2024-04-10T10:30:25.577419163Z     await callback(event)
2024-04-10T10:30:25.577428178Z   File "auto_spy.py", line 5196, in my_event_handler
2024-04-10T10:30:25.577437451Z   File "auto_spy.py", line 4838, in recive_message
2024-04-10T10:30:25.577450225Z   File "auto_spy.py", line 3738, in MasterCmd
2024-04-10T10:30:25.577462870Z   File "auto_spy.py", line 3372, in debugcmd
2024-04-10T10:30:25.577475413Z IndexError: list index out of range

**Comment by OwnerCM** [comment]
遇到同样的问题，还没找到好的解决方案，又不想重装
