### ISSUE TITLE
群晖docker 运行不成功

### ISSUE THREAD

**Issue by fanbin8592** [xieshang/AutoSpy#7]
用虚拟机的docker可以，群晖自带docker不成功。
运行 python3 auto_spy_bot.py
报：
sys info:uname_result(system='Linux', node='auto_spy', release='4.4.180+', version='#42962 SMP Wed Sep 21 10:56:47 CST 2022', machine='x86_64', processor='')
系统为 x86_tx
/autospy
/autospy
加载参数
Traceback (most recent call last):
  File "auto_spy_bot2.py", line 29, in <module>
    main(systype)
  File "auto_spy.py", line 2635, in auto_spy.main
  File "auto_spy.py", line 2094, in auto_spy.LoadConfig
  File "auto_spy.py", line 2095, in auto_spy.LoadConfig
  File "/root/.local/lib/python3.6/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/.local/lib/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/root/.local/lib/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/root/.local/lib/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "auto_spy.yaml", line 2, column 12
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f2d73c1cd68>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 343, in __del__
TypeError: 'NoneType' object is not callable

**Comment by fanbin8592** [comment]
可能还是运行时自动安装依赖要科学上网。用虚拟机可以正常跑的容器导出镜像，再放群晖里也可以正常跑了。
