### ISSUE TITLE
大佬，请问这是什么问题？TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by LQY0606** [xieshang/AutoSpy#8]
root@auto_spy:/autospy# python3 auto_spy_bot2.py
sys info:uname_result(system='Linux', node='auto_spy', release='5.15.0-52-generic', version='#58-Ubuntu SMP Thu Oct 13 08: machine='x86_64', processor='')
系统为 x86_tx
/autospy
/autospy
加载参数
Traceback (most recent call last):
  File "auto_spy_bot2.py", line 29, in <module>
    main(systype)
  File "auto_spy.py", line 2513, in auto_spy.main
  File "auto_spy.py", line 1981, in auto_spy.LoadConfig
  File "auto_spy.py", line 1933, in auto_spy.CheckLic
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f38ef252d68>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 343, in __del__
TypeError: 'NoneType' object is not callable

**Comment by Rishon33** [comment]
我的是arm系统，
  File "/root/.local/lib/python3.6/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/root/.local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/.local/lib/python3.6/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/root/.local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "auto_spy.yaml", line 24, column 12
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f8e96a630>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 343, in __del__
**TypeError: 'NoneType' object is not callable**
sys info:uname_result(system='Linux', node='auto_spy', release='5.15.76-v8+', version='#1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022', machine='aarch64', processor='')
